def funcionprueba():
    try:
        print('correcto')
        return True
    except Exception as e:
        print(e)

funcionprueba()